name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Change to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Build Docker image
        run: |
          docker build -t myusername/my-flask-app:latest .  # Replace 'myusername/my-flask-app' with your Docker Hub repo name

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ashoknath2080/flask-docker-app:latest  # Replace 'myusername/my-flask-app' with your Docker Hub repo name
