name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # Keep this if no newer version is available
        with:
          python-version: '3.8'  # Change to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure pytest is listed in requirements.txt

      - name: Run tests
        run: pytest -v  # Run tests with verbose output
